import {gestorApi} from './src/lib/gestor-api.js';
import {buildXlsxBlob} from './src/lib/xlsx-export.js';
import {DEFAULT_FINANCE} from './src/lib/profit-engine.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number.isFinite(Number(v))?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'N/A';
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const pct=v=>Number.isFinite(Number(v))?`${Number(v).toFixed(2).replace('.',',')}%`:'N/A';
const iso=d=>d.toISOString().slice(0,10);
const parseIso=s=>{const [y,m,d]=String(s).split('-').map(Number);return y&&m&&d?new Date(y,m-1,d):null;};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x;};
const daysInclusive=(a,b)=>Math.floor((new Date(b)-new Date(a))/86400000)+1;

let state={products:[],analytics:null,costs:{},history:{},snapshots:{},jobs:[],finance:{...DEFAULT_FINANCE},rows:[],filtered:[],sortKey:'gmv',sortDir:'desc',page:1,pageSize:10,query:'',status:'all',from:'',to:''};

function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200);}
function formatDate(isoValue){const d=parseIso(isoValue);return d?d.toLocaleDateString('pt-BR'):'—';}
function labelRange(){const span=daysInclusive(state.from,state.to);$('#rangeLabel').textContent=span===1?formatDate(state.from):`${formatDate(state.from)} – ${formatDate(state.to)}`;$('#periodCompare').textContent=state.analytics?`Comparando com ${formatDate(state.analytics.previousRange?.from)} – ${formatDate(state.analytics.previousRange?.to)}`:'—';}
function setDefaultRange(){const end=new Date(),start=addDays(end,-6);state.from=iso(start);state.to=iso(end);$('#dateFrom').value=state.from;$('#dateTo').value=state.to;labelRange();}

function getImage(product){const urls=[...(product?.image?.image_url_list||[]),...(product?.image_info?.image_url_list||[]),...(product?.images||[])].filter(x=>typeof x==='string'&&/^https?:/i.test(x));if(urls[0])return urls[0];const id=product?.image?.image_id_list?.[0]||product?.image_info?.image_id_list?.[0];return id?`https://down-br.img.susercontent.com/file/${id}`:null;}
function getTitle(product){return String(product?.item_name||product?.name||product?.title||`Produto ${product?.item_id||''}`).trim();}
function getPrices(product){const rows=Array.isArray(product?.price_info)?product.price_info:[];const currents=rows.map(x=>num(x.current_price??x.inflated_price_of_current_price??x.price)).filter(Number.isFinite),originals=rows.map(x=>num(x.original_price??x.inflated_price_of_original_price)).filter(Number.isFinite);const current=currents.length?Math.min(...currents):num(product?.price_min??product?.price),original=originals.length?Math.max(...originals):current;return{current,original};}
function latestScore(itemId){const list=Array.isArray(state.history[String(itemId)])?state.history[String(itemId)]:[];const latest=list.at(-1);const snap=state.snapshots[String(itemId)]?.result;return num(latest?.score??snap?.score);}
function financeFor(itemId){const job=state.jobs.find(j=>String(j.itemId)===String(itemId)&&j.status!=='cancelled');return{...state.finance,...(job?.policy?.finance||{})};}
function marginFor(metrics,cost,itemId){if(!metrics||!Number.isFinite(Number(metrics.gmv))||Number(metrics.gmv)<=0||!Number.isFinite(Number(cost)))return{value:null,pct:null,fees:null,cogs:null};const f=financeFor(itemId),gmv=Number(metrics.gmv),sold=Math.max(0,Number(metrics.sold||metrics.orders||0)),orders=Math.max(0,Number(metrics.orders||0)),cogs=Number(cost)*sold,fees=gmv*Number(f.commissionRate||0)+gmv*Number(f.taxRate||0)+orders*(Number(f.fixedFee||0)+Number(f.packagingCost||0)+Number(f.otherCost||0)),value=gmv-cogs-fees-Number(metrics.spend||0);return{value,pct:gmv>0?value/gmv*100:null,fees,cogs};}
function change(current,previous){const c=num(current),p=num(previous);if(c==null||p==null)return null;if(p===0)return c===0?null:{value:null,label:'Novo'};const v=(c-p)/Math.abs(p)*100;return{value:v,label:`${v>=0?'+':''}${v.toFixed(1)}%`};}
function badge(current,previous,{lowerBetter=false}={}){const d=change(current,previous);if(!d)return'';if(d.value==null)return`<span class="badge neutral">${esc(d.label)}</span>`;const improved=lowerBetter?d.value<0:d.value>0,cls=Math.abs(d.value)<0.05?'neutral':improved?'good':'bad';return`<span class="badge ${cls}">${esc(d.label)}</span>`;}

function buildRows(){const current=state.analytics?.current||{},previous=state.analytics?.previous||{},shopId=state.analytics?.shopId||'';state.rows=state.products.map(product=>{const itemId=String(product.item_id),cur=current[itemId]||{impressions:0,clicks:0,spend:0,gmv:0,orders:0,sold:0,roas:null,ctr:null,costPerConversion:0},prev=previous[itemId]||{impressions:0,clicks:0,spend:0,gmv:0,orders:0,sold:0,roas:null,ctr:null,costPerConversion:0},cost=num(state.costs[itemId]?.cost),prices=getPrices(product),margin=marginFor(cur,cost,itemId),previousMargin=marginFor(prev,cost,itemId),score=latestScore(itemId);return{itemId,product,title:getTitle(product),image:getImage(product),url:shopId?`https://shopee.com.br/product/${shopId}/${itemId}`:null,score,cost,price:prices.current,originalPrice:prices.original,cur,prev,margin,previousMargin,hasAds:Number(cur.spend)>0||Number(cur.impressions)>0||Number(cur.clicks)>0||Number(cur.gmv)>0};});applyFilters();}
function sortValue(row,key){if(key==='name')return row.title.toLowerCase();if(key==='score')return row.score??-Infinity;if(key==='cost')return row.cost??-Infinity;if(key==='price')return row.price??-Infinity;if(key==='cpa')return row.cur.costPerConversion??-Infinity;if(key==='gmv')return row.cur.gmv??0;if(key==='roas')return row.cur.roas??-Infinity;if(key==='ctr')return row.cur.ctr??-Infinity;if(key==='marginPct')return row.margin.pct??-Infinity;return 0;}
function applyFilters(){const q=state.query.trim().toLowerCase();state.filtered=state.rows.filter(r=>{if(q&&!`${r.title} ${r.itemId}`.toLowerCase().includes(q))return false;if(state.status==='ads'&&!r.hasAds)return false;if(state.status==='noads'&&r.hasAds)return false;if(state.status==='analyzed'&&r.score==null)return false;if(state.status==='unanalyzed'&&r.score!=null)return false;return true;}).sort((a,b)=>{const av=sortValue(a,state.sortKey),bv=sortValue(b,state.sortKey),dir=state.sortDir==='asc'?1:-1;if(typeof av==='string')return av.localeCompare(bv,'pt-BR')*dir;return((av??-Infinity)-(bv??-Infinity))*dir;});const maxPage=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));if(state.page>maxPage)state.page=maxPage;render();}
function renderSummary(){const totals=state.rows.reduce((a,r)=>{a.gmv+=Number(r.cur.gmv||0);a.spend+=Number(r.cur.spend||0);if(r.hasAds)a.ads++;return a;},{gmv:0,spend:0,ads:0});$('#sumProducts').textContent=state.rows.length.toLocaleString('pt-BR');$('#sumAds').textContent=totals.ads.toLocaleString('pt-BR');$('#sumGmv').textContent=money(totals.gmv);$('#sumSpend').textContent=money(totals.spend);$('#sumRoas').textContent=totals.spend>0?(totals.gmv/totals.spend).toFixed(2):'N/A';}
function priceHtml(r){if(r.price==null)return'N/A';if(r.originalPrice!=null&&r.originalPrice>r.price+0.009)return`<span class="subvalue"><s>${money(r.originalPrice)}</s></span><span class="value">${money(r.price)}</span>`;return`<span class="value">${money(r.price)}</span>`;}
function rowHtml(r){const score=r.score==null?'<button class="score-btn na" data-score="'+esc(r.itemId)+'">N/A</button>':`<button class="score-btn" data-score="${esc(r.itemId)}">${Number(r.score).toFixed(0)}/100</button>`;const thumb=r.image?`<img class="thumb" src="${esc(r.image)}" alt="">`:'<span class="thumb placeholder">—</span>';return`<tr><td>${thumb}</td><td class="name-col"><div class="product-name"><b>${esc(r.title)}</b><small>ID ${esc(r.itemId)}</small></div></td><td>${score}</td><td><span class="value">${r.cost==null?'N/A':money(r.cost)}</span></td><td>${priceHtml(r)}</td><td><span class="value">${r.cur.costPerConversion==null?'N/A':money(r.cur.costPerConversion)}</span>${badge(r.cur.costPerConversion,r.prev.costPerConversion,{lowerBetter:true})}</td><td><span class="value">${money(r.cur.gmv||0)}</span>${badge(r.cur.gmv,r.prev.gmv)}</td><td><span class="value">${r.cur.roas==null?'N/A':Number(r.cur.roas).toFixed(2)}</span>${badge(r.cur.roas,r.prev.roas)}</td><td><span class="value">${r.cur.ctr==null?'N/A':pct(r.cur.ctr)}</span>${badge(r.cur.ctr,r.prev.ctr)}</td><td><span class="value">${r.margin.value==null?'N/A':money(r.margin.value)}</span><span class="subvalue">${r.margin.pct==null?'N/A':pct(r.margin.pct)}</span>${badge(r.margin.value,r.previousMargin.value)}</td></tr>`;}
function render(){renderSummary();const start=(state.page-1)*state.pageSize,end=Math.min(start+state.pageSize,state.filtered.length),slice=state.filtered.slice(start,end);$('#tableBody').innerHTML=slice.length?slice.map(rowHtml).join(''):'<tr><td colspan="10" class="empty">Nenhum produto encontrado com os filtros atuais.</td></tr>';$('#showFrom').textContent=state.filtered.length?start+1:0;$('#showTo').textContent=end;$('#showTotal').textContent=state.filtered.length;const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));$('#pageInfo').textContent=`Página ${state.page} de ${pages}`;$('#prevPage').disabled=state.page<=1;$('#nextPage').disabled=state.page>=pages;$$('th [data-sort]').forEach(b=>{const s=b.querySelector('span');s.textContent=b.dataset.sort===state.sortKey?(state.sortDir==='asc'?'▲':'▼'):'';});$$('[data-score]').forEach(b=>b.onclick=()=>openAnalysis(b.dataset.score));}

async function loadData(){const body=$('#tableBody');body.innerHTML='<tr><td colspan="10" class="loading">Atualizando produtos, Ads e período comparativo…</td></tr>';try{const [products,analytics,local]=await Promise.all([gestorApi.products(),gestorApi.analytics(state.from,state.to),chrome.storage.local.get(['gsProductCostsV1','gsSmartHistoryV1','gsSnapshotsV1','gsJobsV1','gsDefaultAutomation'])]);state.products=products.items||[];state.analytics=analytics;state.costs=local.gsProductCostsV1||{};state.history=local.gsSmartHistoryV1||{};state.snapshots=local.gsSnapshotsV1||{};state.jobs=Array.isArray(local.gsJobsV1)?local.gsJobsV1:[];state.finance={...DEFAULT_FINANCE,...(local.gsDefaultAutomation?.finance||{})};state.page=1;labelRange();buildRows();}catch(e){body.innerHTML=`<tr><td colspan="10" class="empty">${esc(e.message||e)}</td></tr>`;toast('Falha ao carregar a dashboard.');}}

function exportRecords(){return state.filtered.map(r=>({
  'ID do Produto':r.itemId,'Nome do Anúncio':r.title,'Nota Super Análise':r.score??'N/A','Custo Unitário (R$)':r.cost??'N/A','Preço De (R$)':r.originalPrice??'N/A','Preço Por (R$)':r.price??'N/A','Custo por Conversão Ads (R$)':r.cur.costPerConversion??'N/A','Variação Custo/Conversão (%)':change(r.cur.costPerConversion,r.prev.costPerConversion)?.value??'N/A','GMV (R$)':r.cur.gmv??0,'Variação GMV (%)':change(r.cur.gmv,r.prev.gmv)?.value??'N/A','ROAS':r.cur.roas??'N/A','Variação ROAS (%)':change(r.cur.roas,r.prev.roas)?.value??'N/A','CTR (%)':r.cur.ctr??'N/A','Variação CTR (%)':change(r.cur.ctr,r.prev.ctr)?.value??'N/A','Margem Contribuição (R$)':r.margin.value??'N/A','Margem Contribuição (%)':r.margin.pct??'N/A','Variação Margem (%)':change(r.margin.value,r.previousMargin.value)?.value??'N/A','Período Inicial':state.from,'Período Final':state.to}));}
function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function exportCsv(){const rows=exportRecords();if(!rows.length)return toast('Nada para exportar.');const headers=Object.keys(rows[0]),quote=v=>`"${String(v??'').replace(/"/g,'""')}"`,text='\ufeff'+[headers.map(quote).join(';'),...rows.map(r=>headers.map(h=>quote(r[h])).join(';'))].join('\r\n');downloadBlob(new Blob([text],{type:'text/csv;charset=utf-8'}),`gestor-senior-analytics_${state.from}_${state.to}.csv`);}
function exportXlsx(){const rows=exportRecords();if(!rows.length)return toast('Nada para exportar.');const headers=Object.keys(rows[0]),data=rows.map(r=>headers.map(h=>r[h]));downloadBlob(buildXlsxBlob(headers,data,'Anuncios'),`gestor-senior-analytics_${state.from}_${state.to}.xlsx`);}

function detailDimensions(result){return(result?.dimensions||[]).map(d=>`<div class="detail-card"><b>${esc(d.name)} · ${d.score}/${d.maxScore}</b><small>${esc(d.reason||'')}</small></div>`).join('');}
function openAnalysis(itemId){const row=state.rows.find(r=>r.itemId===String(itemId));if(!row)return;const snap=state.snapshots[String(itemId)],result=snap?.result||snap?.analysis||null,history=Array.isArray(state.history[String(itemId)])?state.history[String(itemId)]:[],latest=history.at(-1),score=row.score;$('#modalContent').innerHTML=`<div class="detail-head"><div><h2>${esc(row.title)}</h2><small>ID ${esc(itemId)}</small></div><div class="detail-score">${score==null?'N/A':`${Number(score).toFixed(0)}/100`}</div></div>${result?`<div class="detail-grid">${detailDimensions(result)}</div><h3>Título otimizado</h3><div class="detail-text">${esc(result.optimizedTitle||'Sem sugestão salva.')}</div><h3>Descrição sugerida</h3><div class="detail-text">${esc(result.optimizedDescription||'Sem sugestão salva.')}</div>`:`<div class="detail-card" style="margin-top:12px"><b>${latest?'Há nota registrada pelo motor Super Anúncio.':'Este produto ainda não foi analisado.'}</b><small>${latest?`Última leitura em ${new Date(latest.at).toLocaleString('pt-BR')}. Abra o anúncio para gerar/atualizar o detalhamento completo.`:'Abra o anúncio e rode a Super Análise para preencher score, dimensões e recomendações.'}</small></div>`}<div class="modal-actions"><button id="openProduct" class="primary">Abrir anúncio + Super Análise</button><button id="closeModal2">Fechar</button></div>`;$('#analysisModal').hidden=false;$('#closeModal2').onclick=closeModal;$('#openProduct').onclick=async()=>{if(!row.url)return toast('Não consegui montar o link público deste produto.');const tab=await chrome.tabs.create({url:row.url,active:true});try{await chrome.sidePanel.open({tabId:tab.id});}catch{}closeModal();};}
function closeModal(){$('#analysisModal').hidden=true;}

$('#refreshBtn').onclick=loadData;$('#rangeBtn').onclick=()=>{$('#rangePopover').hidden=!$('#rangePopover').hidden;};$('#exportBtn').onclick=()=>{$('#exportMenu').hidden=!$('#exportMenu').hidden;};$$('[data-export]').forEach(b=>b.onclick=()=>{b.dataset.export==='csv'?exportCsv():exportXlsx();$('#exportMenu').hidden=true;});
$$('[data-range]').forEach(b=>b.onclick=()=>{const type=b.dataset.range,end=new Date(),today=new Date(end.getFullYear(),end.getMonth(),end.getDate());let start=new Date(today),finish=new Date(today);if(type==='yesterday'){start=finish=addDays(today,-1);}else if(type==='3')start=addDays(today,-2);else if(type==='7')start=addDays(today,-6);else if(type==='week'){const day=(today.getDay()+6)%7;start=addDays(today,-day);}else if(type==='month')start=new Date(today.getFullYear(),today.getMonth(),1);$('#dateFrom').value=iso(start);$('#dateTo').value=iso(finish);});
$('#applyRange').onclick=()=>{const from=$('#dateFrom').value,to=$('#dateTo').value,span=daysInclusive(from,to);if(!from||!to||span<1)return toast('Selecione um intervalo válido.');if(span>90)return toast('O intervalo máximo é 90 dias.');state.from=from;state.to=to;state.page=1;$('#rangePopover').hidden=true;labelRange();loadData();};
$('#searchInput').oninput=e=>{state.query=e.target.value;state.page=1;applyFilters();};$('#statusFilter').onchange=e=>{state.status=e.target.value;state.page=1;applyFilters();};$('#pageSize').onchange=e=>{state.pageSize=Number(e.target.value)||10;state.page=1;applyFilters();};$('#prevPage').onclick=()=>{if(state.page>1){state.page--;render();}};$('#nextPage').onclick=()=>{const pages=Math.max(1,Math.ceil(state.filtered.length/state.pageSize));if(state.page<pages){state.page++;render();}};$$('th [data-sort]').forEach(b=>b.onclick=()=>{const key=b.dataset.sort;if(state.sortKey===key)state.sortDir=state.sortDir==='asc'?'desc':'asc';else{state.sortKey=key;state.sortDir=key==='name'?'asc':'desc';}state.page=1;applyFilters();});$('#closeModal').onclick=closeModal;$('#analysisModal').addEventListener('click',e=>{if(e.target===$('#analysisModal'))closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();$('#rangePopover').hidden=true;$('#exportMenu').hidden=true;}});

setDefaultRange();loadData();
