const $=id=>document.getElementById(id);
const statusBadge=$('statusBadge'),currentAction=$('currentAction'),percentText=$('percentText'),progressBar=$('progressBar');
const fields={discovered:$('discovered'),processed:$('processed'),remaining:$('remaining'),screenshots:$('screenshots'),pages:$('pages'),apis:$('apis')};
const startBtn=$('startBtn'),pauseBtn=$('pauseBtn'),resumeBtn=$('resumeBtn'),stopBtn=$('stopBtn'),exportBtn=$('exportBtn'),clearBtn=$('clearBtn'),message=$('message');
const radio=$('radio'),stationSelect=$('stationSelect'),playBtn=$('playBtn'),nextBtn=$('nextBtn'),volume=$('volume'),autoRadio=$('autoRadio');
let lastState=null;

function send(type,extra={}){return chrome.runtime.sendMessage({type,...extra});}
function labelStatus(s){return({idle:'Parado',running:'Mapeando',paused:'Pausado',stopping:'Parando',stopped:'Interrompido',completed:'Concluído',error:'Erro'})[s]||'Parado';}
function fmtAgo(iso){if(!iso)return'Nenhuma atividade.';const sec=Math.max(0,Math.round((Date.now()-new Date(iso).getTime())/1000));return sec<2?'Atividade agora':`Última atividade há ${sec}s`;}
function render(state){lastState=state||null;const s=state?.status||'idle',pct=state?.percent||0;statusBadge.className=`badge ${s}`;statusBadge.textContent=labelStatus(s);percentText.textContent=`${pct}%`;progressBar.style.width=`${pct}%`;currentAction.textContent=state?.currentAction?.label?`Testando: ${state.currentAction.label}`:(s==='completed'?'Mapeamento concluído':'Pronto para mapear');fields.discovered.textContent=state?.discovered||0;fields.processed.textContent=state?.processed||0;fields.remaining.textContent=state?.queue?.length||0;fields.screenshots.textContent=state?.screenshots||0;fields.pages.textContent=state?.pages?.length||0;fields.apis.textContent=state?.apiCount||0;$('heartbeat').textContent=fmtAgo(state?.lastHeartbeat);const active=['running','paused','stopping'].includes(s);startBtn.disabled=active;pauseBtn.disabled=s!=='running';resumeBtn.disabled=s!=='paused';stopBtn.disabled=!['running','paused'].includes(s);exportBtn.disabled=!state||!(state.processed||state.screenshots||state.pages?.length);}
async function refresh(){try{const r=await send('GS_MAPPER_STATUS');if(r?.ok)render(r.state);}catch{}finally{setTimeout(refresh,1000);}}
function show(text,error=false){message.textContent=text||'';message.style.color=error?'#ff9fb2':'#8fdbff';}

startBtn.addEventListener('click',async()=>{show('Iniciando…');const options={maxDepth:Number($('maxDepth').value),maxActions:Number($('maxActions').value),captureScreens:$('captureScreens').checked};const r=await send('GS_MAPPER_START',{options});if(!r?.ok)return show(r?.error||'Não foi possível iniciar.',true);render(r.state);show('Mapeamento iniciado.');if(autoRadio.checked)playRadio();});
pauseBtn.addEventListener('click',async()=>{const r=await send('GS_MAPPER_PAUSE');if(r?.ok){render(r.state);show('Mapeamento pausado.');}});
resumeBtn.addEventListener('click',async()=>{const r=await send('GS_MAPPER_RESUME');if(r?.ok){render(r.state);show('Mapeamento retomado.');}});
stopBtn.addEventListener('click',async()=>{const r=await send('GS_MAPPER_STOP');if(r?.ok){render(r.state);show('Parada segura solicitada.');}});
clearBtn.addEventListener('click',async()=>{if(lastState&&['running','paused'].includes(lastState.status))return show('Pare o mapeamento antes de limpar.',true);const r=await send('GS_MAPPER_CLEAR');if(r?.ok){render(null);show('Sessão limpa.');}});

function playRadio(){radio.src=stationSelect.value;radio.volume=Number(volume.value);radio.play().then(()=>{playBtn.textContent='⏸ Pausar';}).catch(()=>show('O navegador bloqueou a reprodução automática. Toque em “Tocar”.',true));}
playBtn.addEventListener('click',()=>{if(radio.paused)playRadio();else{radio.pause();playBtn.textContent='▶ Tocar';}});
nextBtn.addEventListener('click',()=>{stationSelect.selectedIndex=(stationSelect.selectedIndex+1)%stationSelect.options.length;playRadio();});
stationSelect.addEventListener('change',()=>{if(!radio.paused)playRadio();});
volume.addEventListener('input',()=>radio.volume=Number(volume.value));
radio.addEventListener('pause',()=>playBtn.textContent='▶ Tocar');radio.addEventListener('play',()=>playBtn.textContent='⏸ Pausar');

const enc=new TextEncoder();
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function u16(n){return[n&255,(n>>>8)&255]}function u32(n){return[n&255,(n>>>8)&255,(n>>>16)&255,(n>>>24)&255]}
function concat(parts){const size=parts.reduce((a,p)=>a+p.length,0),out=new Uint8Array(size);let o=0;for(const p of parts){out.set(p,o);o+=p.length;}return out;}
function dataUrlBytes(dataUrl){const b64=String(dataUrl||'').split(',')[1]||'',bin=atob(b64),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out;}
function zipStore(files){const locals=[],centrals=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=f.bytes instanceof Uint8Array?f.bytes:enc.encode(String(f.text||'')),crc=crc32(data);const local=concat([new Uint8Array([80,75,3,4]),new Uint8Array(u16(20)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u32(crc)),new Uint8Array(u32(data.length)),new Uint8Array(u32(data.length)),new Uint8Array(u16(name.length)),new Uint8Array(u16(0)),name,data]);locals.push(local);const central=concat([new Uint8Array([80,75,1,2]),new Uint8Array(u16(20)),new Uint8Array(u16(20)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u32(crc)),new Uint8Array(u32(data.length)),new Uint8Array(u32(data.length)),new Uint8Array(u16(name.length)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u32(0)),new Uint8Array(u32(offset)),name]);centrals.push(central);offset+=local.length;}const body=concat(locals),central=concat(centrals),end=concat([new Uint8Array([80,75,5,6]),new Uint8Array(u16(0)),new Uint8Array(u16(0)),new Uint8Array(u16(files.length)),new Uint8Array(u16(files.length)),new Uint8Array(u32(central.length)),new Uint8Array(u32(body.length)),new Uint8Array(u16(0))]);return new Blob([body,central,end],{type:'application/zip'});}

exportBtn.addEventListener('click',async()=>{show('Montando ZIP…');const r=await send('GS_MAPPER_EXPORT');if(!r?.ok)return show(r?.error||'Falha ao exportar.',true);const {state,screens,apis}=r.data||{};const summary={sessionId:state?.sessionId,status:state?.status,startedAt:state?.startedAt,finishedAt:state?.updatedAt,progress:state?.percent,discovered:state?.discovered,processed:state?.processed,skipped:state?.skipped,screenshots:screens?.length||0,pages:state?.pages?.length||0,apis:apis?.length||0,errors:state?.errors?.length||0};const cleanState={...state,queue:state?.queue||[]};const files=[{name:'resumo.json',text:JSON.stringify(summary,null,2)},{name:'mapa.json',text:JSON.stringify(cleanState,null,2)},{name:'apis.json',text:JSON.stringify(apis||[],null,2)},{name:'logs/execucao.json',text:JSON.stringify(state?.logs||[],null,2)},{name:'logs/erros.json',text:JSON.stringify(state?.errors||[],null,2)}];for(const s of screens||[])if(s.dataUrl)files.push({name:s.name||`screenshots/${Date.now()}.png`,bytes:dataUrlBytes(s.dataUrl)});const blob=zipStore(files),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Motor-Senior-Mapeamento-${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);show(`ZIP gerado com ${files.length} arquivos.`);});

refresh();
