const $=s=>document.querySelector(s);const send=m=>chrome.runtime.sendMessage(m);const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#tab-'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='automacao')loadJobs();});
$('#analyze').onclick=async()=>{const b=$('#analyze');b.disabled=true;b.textContent='Analisando anúncio + concorrentes…';try{const r=await send({type:'GS_ANALYZE_CURRENT'});if(!r.ok)throw new Error(r.error);renderAnalysis(r.data);}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='✨ Analisar anúncio atual'}};
function renderAnalysis(d){$('#analysisEmpty').hidden=true;const a=$('#analysis');a.hidden=false;const r=d.result||{};a.innerHTML=`<div class="score"><div><strong>${esc(d.product?.title||'Anúncio')}</strong><small style="display:block;color:#8fa1b5">${d.competitors?.length||0} concorrente(s) coletado(s)</small></div><b>${r.score}/100</b></div><div class="card"><b>${esc(r.summary)}</b>${(r.dimensions||[]).map(x=>`<div class="dimension"><div><strong>${esc(x.name)}</strong><b>${x.score}/${x.maxScore}</b></div><small>${esc(x.reason)}</small></div>`).join('')}</div>${r.roasStrategy?`<div class="card"><b>Ads: ${esc(r.roasStrategy.title)}</b><p>${esc(r.roasStrategy.message)}</p>${Number.isFinite(Number(r.roasStrategy.suggestedTarget))?`<div class="proposal">Meta sugerida: <b>${Number(r.roasStrategy.suggestedTarget).toFixed(2)}</b></div>`:''}</div>`:''}<div class="card"><b>Correções sugeridas</b><div class="proposal"><small>Título</small><br>${esc(r.optimizedTitle)}</div><div class="proposal"><small>Descrição</small><br>${esc(String(r.optimizedDescription||'').slice(0,500))}${String(r.optimizedDescription||'').length>500?'…':''}</div></div>`;if(d.product?.itemId){$('#jobItem').value=d.product.itemId;$('#jobTitle').value=d.product.title||'';}};
$('#createJob').onclick=async()=>{const itemId=$('#jobItem').value.trim();if(!itemId)return toast('Informe o ID do item.');const cost=Number($('#jobCost').value);if(Number.isFinite(cost))await send({type:'GS_SAVE_COST',itemId,cost});const job={itemId,title:$('#jobTitle').value.trim(),frequencyDays:Number($('#jobFreq').value),policy:{enabled:true,mode:$('#jobMode').value,maxRoasChangePct:Number($('#maxRoas').value)||10,allowRoas:true,allowBudget:true,allowProtectionReset:$('#allowProtection').checked,allowPrice:false,allowTitle:false,allowDescription:false,finance:{minMarginPct:Number($('#minMargin').value)||20,minProfit:Number($('#minProfit').value)||8,maxWeeklyAdsSpend:Number($('#maxSpend').value)||300}}};const r=await send({type:'GS_CREATE_JOB',job});if(r.ok){toast('Manutenção criada.');loadJobs()}else toast(r.error)};
async function loadJobs(){const r=await send({type:'GS_LIST_JOBS'});const box=$('#jobs');box.innerHTML=(r.jobs||[]).filter(j=>j.status!=='cancelled').map(j=>`<div class="job"><b>${esc(j.title||j.itemId)}</b><small style="display:block;color:#8fa1b5">a cada ${j.frequencyDays} dias · ${esc(j.policy?.mode||'approve')}</small><div class="actions"><button data-run="${esc(j.id)}">Executar agora</button><button data-cancel="${esc(j.id)}">Cancelar</button></div></div>`).join('')||'<div class="empty">Nenhuma manutenção ativa.</div>';box.querySelectorAll('[data-run]').forEach(b=>b.onclick=async()=>{b.disabled=true;const x=await send({type:'GS_RUN_JOB_NOW',id:b.dataset.run});toast(x.ok?'Ciclo concluído.':x.error);b.disabled=false});box.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{await send({type:'GS_CANCEL_JOB',id:b.dataset.cancel});loadJobs()});}
$('#researchCapture').onchange=async e=>{const r=await send({type:'GS_SET_RESEARCH_CAPTURE',enabled:e.target.checked});toast(r.ok?'Configuração salva.':r.error)};
$('#clearCapture').onclick=async()=>{await chrome.storage.local.remove('gsAutoMapperCapturesV1');toast('Capturas locais apagadas.')};
(async()=>{const r=await send({type:'GS_GET_STATE'});$('#researchCapture').checked=r.state?.gsResearchCapture===true;})();
