const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], send=m=>chrome.runtime.sendMessage(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>Number.isFinite(Number(v))?Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}):'—';
let lastAnalysis=null, loadedJobs=[], categories=[], selected=new Set(), collectorState='idle', shopeeTabId=null;
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
function tab(name){$$('nav button,.tab').forEach(x=>x.classList.remove('active'));$(`nav button[data-tab="${name}"]`)?.classList.add('active');$(`#tab-${name}`)?.classList.add('active');if(name==='home')refreshHome();if(name==='auto')loadJobs();if(name==='resale')refreshResale();}
$$('nav button').forEach(b=>b.onclick=()=>tab(b.dataset.tab));

async function findShopeeTab(){const [active]=await chrome.tabs.query({active:true,currentWindow:true});if(active?.url?.startsWith('https://shopee.com.br/'))return active;const tabs=await chrome.tabs.query({url:'https://shopee.com.br/*'});return tabs[0]||null;}
async function refreshHome(){const [s,j]=await Promise.all([send({type:'GS_COLLECTOR_STATS'}),send({type:'GS_LIST_JOBS'})]);const st=s.stats||{};$('#homeIndexed').textContent=st.total||0;$('#homeShops').textContent=st.shops||0;$('#homeMedian').textContent=money(st.medianPrice);$('#homeJobs').textContent=(j.jobs||[]).filter(x=>x.status!=='cancelled').length;}

async function runAnalysis(){const b=$('#smartAnalyze');b.disabled=true;b.textContent='Analisando…';try{const r=await send({type:'GS_SMART_ANALYZE'});if(!r?.ok)throw new Error(r?.error||'Falha na análise.');lastAnalysis=r.data;renderAnalysis(r.data);$('#homeLast').innerHTML=`<b>${esc(r.data.product?.title||'Produto')}</b><br>Nota ${r.data.analysis?.score}/100 · ${r.data.competitors?.length||0} concorrentes · ${r.data.plan?.length||0} ação(ões) sugerida(s)`;tab('analyze');}catch(e){toast(e.message)}finally{b.disabled=false;b.textContent='Analisar'}}
$('#smartAnalyze').onclick=runAnalysis;$('#homeAnalyze').onclick=runAnalysis;

function trendParts(trend){if(!trend)return['Primeira leitura registrada para este anúncio.'];const out=[];if(trend.score!=null)out.push(`nota ${trend.score>=0?'+':''}${trend.score}`);if(trend.roas!=null)out.push(`ROAS ${trend.roas>=0?'+':''}${Number(trend.roas).toFixed(2)}`);if(trend.orders!=null)out.push(`pedidos ${trend.orders>=0?'+':''}${trend.orders}`);if(trend.sold!=null)out.push(`vendidos ${trend.sold>=0?'+':''}${trend.sold}`);if(trend.views!=null)out.push(`visualizações ${trend.views>=0?'+':''}${trend.views}`);return out.length?[`Comparado à última leitura: ${out.join(' · ')}`]:['Há histórico, mas ainda sem métricas comparáveis suficientes.'];}

function planDetails(x){
  if((x.type==='roas'||x.type==='rollback_roas')&&Number.isFinite(Number(x.target)))return `Meta ${Number(x.current ?? lastAnalysis?.campaign?.targetRoas ?? 0).toFixed(2)} → ${Number(x.target).toFixed(2)}`;
  if(x.type==='price'&&Number.isFinite(Number(x.target)))return `${money(x.current)} → ${money(x.target)}${x.safe===false?' · bloqueado pela proteção financeira':''}`;
  if(x.type==='title'&&x.suggested)return String(x.suggested).slice(0,180);
  if(x.type==='description'&&x.suggested)return String(x.suggested).slice(0,220)+'…';
  return '';
}

function renderAnalysis(d){
  const r=d.analysis||{},p=d.product||{};$('#analysisEmpty').hidden=true;$('#analysisResult').hidden=false;$('#autoItem').value=p.itemId||'';$('#autoTitle').value=p.title||'';$('#autoUrl').value=p.url||'';
  if(Number.isFinite(Number(d.cost))){$('#analysisCost').value=d.cost;$('#autoCost').value=d.cost;}
  const trendText=trendParts(d.trend)[0],plan=d.plan||[],actionable=plan.filter(x=>x.actionable!==false&&(x.type==='roas'||x.type==='rollback_roas')).length;
  $('#analysisResult').innerHTML=`<div class="scorebox"><div><strong>${esc(p.title||'Anúncio')}</strong><div class="source">${d.source?.indexed||0} concorrente(s) da base + ${d.source?.live||0} da busca ao vivo</div></div><b class="score">${r.score}/100</b></div><div class="card"><b>${esc(r.summary)}</b><p class="muted">${esc(trendText)}</p>${(r.dimensions||[]).map(x=>`<div class="dimension"><div class="row"><b>${esc(x.name)}</b><b>${x.score}/${x.maxScore}</b></div><small class="muted">${esc(x.reason)}</small></div>`).join('')}</div><div class="card"><div class="row"><b>Plano de melhoria</b><span class="pill">${plan.length} item(ns)</span></div>${plan.length?plan.map((x,i)=>`<div class="plan p${Math.min(9,x.priority)}"><div class="row"><b>${i+1}. ${esc(x.title)}</b><span class="pill">${x.actionable?'executável':'aprovação'}</span></div><small>${esc(x.reason)}</small>${planDetails(x)?`<div class="plan-detail">${esc(planDetails(x))}</div>`:''}${x.type==='roas'&&Number.isFinite(Number(x.target))?`<div class="actions"><button class="primary" data-apply-roas="${i}">Aplicar ROAS ${Number(x.target).toFixed(2)}</button></div>`:''}${x.type==='rollback_roas'&&Number.isFinite(Number(x.target))?`<div class="actions"><button class="danger" data-rollback-roas="${i}">Reverter para ${Number(x.target).toFixed(2)}</button></div>`:''}</div>`).join(''):'<p class="muted">Nenhuma mudança urgente detectada.</p>'}${plan.length?`<button id="applySafePlan" class="primary big safe-action">⚡ Aplicar melhorias seguras${actionable?` (${actionable})`:''}</button>`:''}</div><div class="card"><b>Título otimizado</b><p>${esc(r.optimizedTitle||'')}</p><button id="copyTitle">Copiar título</button></div><div class="card"><b>Descrição sugerida</b><p>${esc(String(r.optimizedDescription||'').slice(0,900))}${String(r.optimizedDescription||'').length>900?'…':''}</p><button id="copyDescription">Copiar descrição</button></div><div class="card"><div class="row"><b>Histórico deste anúncio</b><button id="loadHistory">Carregar</button></div><div id="analysisHistory" class="history muted">Use o histórico para comparar antes/depois das mudanças.</div></div><button id="scheduleFromAnalysis" class="primary big">Agendar melhoria periódica</button>`;
  $('#copyTitle')?.addEventListener('click',()=>navigator.clipboard.writeText(r.optimizedTitle||'').then(()=>toast('Título copiado.')));$('#copyDescription')?.addEventListener('click',()=>navigator.clipboard.writeText(r.optimizedDescription||'').then(()=>toast('Descrição copiada.')));
  $('#scheduleFromAnalysis')?.addEventListener('click',()=>{tab('auto');toast('Dados do anúncio preenchidos. Ajuste os limites e confirme.');});
  $('#loadHistory')?.addEventListener('click',()=>loadAnalysisHistory(p.itemId));
  $('#applySafePlan')?.addEventListener('click',async()=>{if(!confirm('Aplicar agora somente as melhorias que já têm execução segura validada? Título, descrição e preço continuarão aguardando aprovação.'))return;const btn=$('#applySafePlan');btn.disabled=true;const q=await send({type:'GS_APPLY_SAFE_PLAN',payload:{itemId:p.itemId,plan:d.plan,campaign:d.campaign}});if(q.ok){toast(q.data?.message||'Plano processado.');if(q.data?.executed?.length)setTimeout(runAnalysis,900);}else toast(q.error);btn.disabled=false;});
  $$('[data-apply-roas],[data-rollback-roas]').forEach(btn=>btn.onclick=async()=>{const idx=Number(btn.dataset.applyRoas??btn.dataset.rollbackRoas),x=d.plan[idx];if(!x)return;if(!confirm(`Alterar a Meta de ROAS para ${Number(x.target).toFixed(2)}?`))return;btn.disabled=true;const q=await send({type:'GS_APPLY_ROAS',payload:{itemId:p.itemId,campaignId:x.campaignId,currentTarget:x.current??d.campaign?.targetRoas,target:x.target,mode:d.campaign?.controlMode||'manual'}});toast(q.ok?'ROAS alterado. A mudança foi registrada.':q.error);btn.disabled=false;if(q.ok)setTimeout(runAnalysis,900);});
}

async function loadAnalysisHistory(itemId){const box=$('#analysisHistory');box.textContent='Carregando…';const [h,a]=await Promise.all([send({type:'GS_GET_SMART_HISTORY',itemId}),send({type:'GS_GET_ACTION_LOG',itemId})]);const rows=(h.history||[]).slice(-8).reverse();if(!rows.length)return box.textContent='Ainda não há histórico suficiente.';box.innerHTML=rows.map(x=>`<div class="history-row"><span>${new Date(x.at).toLocaleString('pt-BR')}</span><b>${x.score??'—'}/100</b><span>ROAS ${x.roas==null?'—':Number(x.roas).toFixed(2)}</span><span>Pedidos ${x.orders??'—'}</span>${x.action?`<span class="history-action">mudança: ${esc(x.action.type)} ${x.action.target??''}</span>`:''}</div>`).join('')+`<small>${(a.actions||[]).length} ação(ões) registrada(s) no total.</small>`;}

$('#saveAnalysisCost').onclick=async()=>{if(!lastAnalysis?.product?.itemId)return toast('Analise um anúncio primeiro.');const cost=Number($('#analysisCost').value);if(!Number.isFinite(cost)||cost<0)return toast('Custo inválido.');const r=await send({type:'GS_SAVE_COST',itemId:lastAnalysis.product.itemId,cost});if(r.ok){$('#autoCost').value=cost;lastAnalysis.cost=cost;toast('Custo salvo para este produto.');}else toast(r.error)};

$('#createAuto').onclick=async()=>{
  const itemId=$('#autoItem').value.trim();if(!itemId)return toast('Informe o ID do item.');const cost=Number($('#autoCost').value),mode=$('#autoMode').value;if(mode==='automatic'&&(!Number.isFinite(cost)||cost<0))return toast('No modo automático, informe o custo do produto antes de criar a manutenção.');if(Number.isFinite(cost)&&cost>=0)await send({type:'GS_SAVE_COST',itemId,cost});
  const url=$('#autoDeepAudit').checked?$('#autoUrl').value.trim():'';
  const job={itemId,title:$('#autoTitle').value.trim(),url,frequencyDays:Number($('#autoFreq').value),policy:{enabled:true,mode,maxRoasChangePct:Math.min(15,Math.max(1,Number($('#autoRoasDelta').value)||10)),allowRoas:true,allowBudget:true,allowProtectionReset:$('#autoProtection').checked,allowPrice:true,allowTitle:true,allowDescription:true,scheduledLiveCompetitors:$('#autoLiveCompetitors').checked,rollbackOnWorsePerformance:true,finance:{minMarginPct:Number($('#autoMargin').value)||20,minProfit:Number($('#autoProfit').value)||8,maxWeeklyAdsSpend:Number($('#autoSpend').value)||300}}};
  const r=await send({type:'GS_CREATE_JOB',job});if(r.ok){toast('Manutenção criada.');loadJobs()}else toast(r.error)
};

function lastRoasProposal(audit){if(audit?.rollback)return{type:'rollback_roas',target:audit.rollback.target,current:audit.campaign?.targetRoas,campaignId:audit.campaign?.campaignId,reason:audit.rollback.reason};return(audit?.decision?.proposals||[]).find(x=>x.type==='change_roas_target')||null;}
function jobReviewHtml(j){const last=j.history?.at(-1)?.result,a=last?.audit;if(!a)return'<small class="muted">Ainda sem revisão executada.</small>';if(last?.ok===false)return`<small class="status-bad">Falha: ${esc(last.reason||last.error||'erro na revisão')}</small>`;const score=a.listingAudit?.analysis?.score,recs=a.summary?.recommendations?.length||0,exec=a.executed?.length||0,listing=a.listingAudit?.listingDecision?.proposals||[],roas=lastRoasProposal(a);return`<div class="job-summary"><span>Última revisão: ${score==null?'Ads apenas':`nota ${score}/100`}</span><span>${recs} recomendação(ões)</span><span>${exec} executada(s)</span></div>${a.listingAudit?.error?`<small class="status-warn">Conteúdo não reavaliado: ${esc(a.listingAudit.error)}</small>`:''}${listing.length?`<details><summary>${listing.length} melhoria(s) de conteúdo/preço aguardando aprovação</summary>${listing.map(x=>`<div class="proposal-note"><b>${x.type==='change_title'?'Título':x.type==='change_description'?'Descrição':x.type==='change_price'?'Preço':'Anúncio'}</b><span>${esc(x.reason||'')}</span>${x.type==='change_price'?`<small>${money(x.current)} → ${money(x.target)}</small>`:''}</div>`).join('')}</details>`:''}${j.policy?.mode==='approve'&&roas?`<button class="primary approve-roas" data-approve="${esc(j.id)}">Aprovar ROAS ${Number(roas.target).toFixed(2)}</button>`:''}`;}

async function loadJobs(){const r=await send({type:'GS_LIST_JOBS'}),box=$('#jobList');loadedJobs=(r.jobs||[]).filter(j=>j.status!=='cancelled');box.innerHTML=loadedJobs.length?loadedJobs.map(j=>`<div class="job"><div class="row"><b>${esc(j.title||j.itemId)}</b><span class="pill">${j.policy?.mode==='automatic'?'AUTO ADS':'APROVAÇÃO'}</span></div><small class="muted">a cada ${j.frequencyDays} dias · próxima ${j.nextRunAt?new Date(j.nextRunAt).toLocaleString('pt-BR'):'—'}</small>${j.url?'<small class="status-good">Auditoria profunda ativa</small>':'<small class="status-warn">Sem URL: revisão de conteúdo não será aberta automaticamente.</small>'}${jobReviewHtml(j)}<div class="actions"><button data-run="${esc(j.id)}">Executar agora</button>${j.url?`<button data-open="${esc(j.id)}">Abrir anúncio</button>`:''}<button data-cancel="${esc(j.id)}" class="danger">Cancelar</button></div></div>`).join(''):'<div class="empty">Nenhuma manutenção ativa.</div>';
  box.querySelectorAll('[data-run]').forEach(b=>b.onclick=async()=>{b.disabled=true;b.textContent='Executando…';const x=await send({type:'GS_RUN_JOB_NOW',id:b.dataset.run});toast(x.ok?(x.result?.status==='executed'?'Ciclo concluído com ação automática.':'Ciclo concluído; confira as recomendações.'):x.error);b.disabled=false;b.textContent='Executar agora';loadJobs();});
  box.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=async()=>{await send({type:'GS_CANCEL_JOB',id:b.dataset.cancel});loadJobs();});
  box.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{const j=loadedJobs.find(x=>x.id===b.dataset.open);if(j?.url)chrome.tabs.create({url:j.url,active:true});});
  box.querySelectorAll('[data-approve]').forEach(b=>b.onclick=async()=>{const j=loadedJobs.find(x=>x.id===b.dataset.approve),audit=j?.history?.at(-1)?.result?.audit,p=lastRoasProposal(audit);if(!j||!audit||!p)return toast('Proposta não encontrada.');if(!confirm(`Aprovar mudança de ROAS para ${Number(p.target).toFixed(2)}?`))return;b.disabled=true;const q=await send({type:'GS_APPLY_ROAS',payload:{itemId:j.itemId,campaignId:p.campaignId||audit.campaign?.campaignId,currentTarget:p.current??audit.campaign?.targetRoas,target:p.target,mode:audit.campaign?.controlMode||'manual'}});toast(q.ok?'Mudança aprovada e registrada.':q.error);b.disabled=false;if(q.ok)loadJobs();});
}

function renderCollectorStatus(s={}){collectorState=s.state||collectorState;const done=s.completed||0,total=s.total||0;$('#collectBar').style.width=total?`${Math.min(100,done/total*100)}%`:(done?'12%':'0');$('#collectCount').textContent=total?`${done} / ${total} arquivos`:`${done} arquivo(s)`;$('#collectErrors').textContent=`${s.errors||0} erro(s)`;$('#collectStatus').textContent=s.message||'Pronto.';$('#startCollection').disabled=['running','pausing','paused'].includes(collectorState);$('#pauseCollection').disabled=!['running','pausing','paused'].includes(collectorState)||collectorState==='pausing';$('#pauseCollection').textContent=collectorState==='paused'?'Continuar':'Pausar';$('#cancelCollection').disabled=!['running','pausing','paused'].includes(collectorState);}
async function refreshResale(){const r=await send({type:'GS_COLLECTOR_STATS'}),s=r.stats||{};$('#resaleTotal').textContent=s.total||0;$('#resaleShops').textContent=s.shops||0;$('#resaleMedian').textContent=money(s.medianPrice);$('#resaleSold').textContent=Number(s.totalHistoricalSold||0).toLocaleString('pt-BR');$('#resaleTop').innerHTML=(s.top||[]).map((x,i)=>`<div class="topitem"><span>${x.imageUrl?`<img src="${esc(x.imageUrl)}">`:`#${i+1}`}</span><span><b>${esc(x.title)}</b><small>${money(x.price)} · ${Number(x.sold||0).toLocaleString('pt-BR')} vendidos</small></span><span class="pill">#${i+1}</span></div>`).join('')||'<p class="muted">A base ainda está vazia. Faça uma coleta abaixo.</p>';if(!categories.length)loadCategories();const tab=await findShopeeTab();shopeeTabId=tab?.id||null;if(tab){try{const j=await chrome.tabs.sendMessage(tab.id,{type:'GET_JOB'});if(j?.job)renderCollectorStatus({state:j.job.state,completed:j.job.completed,total:j.job.total,errors:j.job.failures?.length,message:j.job.state==='paused'?'Coleta pausada.':`${j.job.completed||0} arquivo(s) salvo(s).`});}catch{}}}
$('#refreshResale').onclick=refreshResale;
$$('input[name="collectMode"]').forEach(r=>r.onchange=()=>{const cat=$('input[name="collectMode"]:checked').value==='category';$('#categoryBox').hidden=!cat;$('#searchBox').hidden=cat;if(cat&&!categories.length)loadCategories();});
async function loadCategories(){const tab=await findShopeeTab();if(!tab)return $('#categoryList').innerHTML='<span class="muted">Abra a Shopee Brasil primeiro.</span>';shopeeTabId=tab.id;try{const r=await chrome.tabs.sendMessage(tab.id,{type:'GET_CATEGORIES'});if(!r?.ok)throw new Error(r?.error);categories=r.categories||[];renderCategories();}catch(e){$('#categoryList').innerHTML=`<span class="muted">${esc(e.message||'Recarregue a Shopee após atualizar a extensão.')}</span>`;}}
function renderCategories(){const q=$('#categoryFilter').value.trim().toLowerCase(),list=categories.filter(c=>`${c.label} ${c.parent||''} ${c.id}`.toLowerCase().includes(q)).slice(0,300);$('#categoryList').innerHTML=list.map(c=>`<label class="cat"><input type="checkbox" data-catid="${esc(c.id)}" ${selected.has(c.id)?'checked':''}><span>${esc(c.label)}<small>${c.parent?esc(c.parent)+' · ':''}ID ${esc(c.id)}</small></span></label>`).join('')||'<span class="muted">Nenhuma categoria encontrada.</span>';$('#categorySelected').textContent=`${selected.size} selecionada(s)`;$$('[data-catid]').forEach(x=>x.onchange=()=>{if(x.checked)selected.add(x.dataset.catid);else selected.delete(x.dataset.catid);$('#categorySelected').textContent=`${selected.size} selecionada(s)`;});}
$('#categoryFilter').oninput=renderCategories;$('#selectVisible').onclick=()=>{$$('[data-catid]').forEach(x=>selected.add(x.dataset.catid));renderCategories();};$('#clearCategories').onclick=()=>{selected.clear();renderCategories();};
$('#startCollection').onclick=async()=>{const tab=await findShopeeTab();if(!tab)return toast('Abra a Shopee Brasil primeiro.');shopeeTabId=tab.id;const mode=$('input[name="collectMode"]:checked').value;let targets;if(mode==='search'){const term=$('#resaleTerm').value.trim();if(!term)return toast('Digite um termo.');targets=[{type:'search',term,name:term,slug:term.toLowerCase().replace(/\s+/g,'_')}];}else{targets=categories.filter(c=>selected.has(c.id));if(!targets.length)return toast('Selecione ao menos uma categoria.');}const r=await chrome.tabs.sendMessage(tab.id,{type:'START_COLLECTION',targets,pageMode:$('#collectPages').value,delayMs:Number($('#collectDelay').value)});if(r?.ok)renderCollectorStatus({state:'running',completed:0,total:$('#collectPages').value==='all'?0:targets.length,message:'Iniciando coleta…'});else toast(r?.error||'Não foi possível iniciar.');};
$('#pauseCollection').onclick=async()=>{if(!shopeeTabId)return;await chrome.tabs.sendMessage(shopeeTabId,{type:collectorState==='paused'?'CONTINUE_COLLECTION':'PAUSE_COLLECTION'});};$('#cancelCollection').onclick=async()=>{if(!shopeeTabId)return;await chrome.tabs.sendMessage(shopeeTabId,{type:'CANCEL_COLLECTION'});};
chrome.runtime.onMessage.addListener(m=>{if(m?.type==='COLLECTOR_STATUS'){renderCollectorStatus(m);if(['finished','finished_with_errors'].includes(m.state))setTimeout(refreshResale,800);}});

$('#researchCapture').onchange=async e=>{const r=await send({type:'GS_SET_RESEARCH_CAPTURE',enabled:e.target.checked});toast(r.ok?'Configuração salva.':r.error)};$('#clearTechnical').onclick=async()=>{await chrome.storage.local.remove('gsAutoMapperCapturesV1');toast('Capturas técnicas apagadas.')};$('#clearIndex').onclick=async()=>{if(!confirm('Apagar a base local criada pelo Coletor 3.1? Os JSONs já baixados não serão apagados.'))return;const r=await send({type:'GS_CLEAR_COLLECTOR_INDEX'});if(r.ok){toast('Índice limpo.');refreshHome();refreshResale();}};

(async()=>{const st=await send({type:'GS_GET_STATE'});$('#researchCapture').checked=st.state?.gsResearchCapture===true;refreshHome();})();
