(() => {
  'use strict';
  const SOURCE='GESTOR_SENIOR_EXTENSION';
  if(window.__GESTOR_SENIOR_PAGE_HOOKED__)return;window.__GESTOR_SENIOR_PAGE_HOOKED__=true;
  let enabled=false;
  const ALWAYS=[/\/api\/pas\/v1\/rebate\/campaign_get\//i,/\/api\/pas\/v1\/product\/(?:edit|publish)\//i,/\/api\/pas\/v1\/homepage\/mass_edit\//i];
  const SENSITIVE=/(token|authorization|auth|cookie|csrf|spc_cds|signature|password|secret|session|access[_-]?key)/i;
  const NOISE=[/remote-component\/manifest/i,/web-(?:custom|performance)\/event\/json/i,/config-monitor\/event\/json/i,/\/configs\/_fetch/i,/\/abtest\//i,/get_ab_test_toggle/i,/\/signature(?:\?|$)/i,/webchat\/api\/.*\/sync/i];
  const BUSINESS=/(order|shipment|logistic|invoice|product|mpsku|stock|inventory|return|refund|affiliate|bidding|ads|campaign|marketing|promotion|homepage|topup|finance|wallet|performance|traffic|metric|report|sale|gmv|optimizer|seller_center)/i;
  const endpointOf=url=>{try{const u=new URL(url,location.href);return u.origin+u.pathname}catch{return String(url||'').split('?')[0]}};
  const safeBody=(body,depth=0)=>{if(depth>7)return'[TRUNCATED]';if(Array.isArray(body))return body.slice(0,100).map(v=>safeBody(v,depth+1));if(body&&typeof body==='object'){const out={};for(const[k,v]of Object.entries(body))out[k]=SENSITIVE.test(k)?'[REDACTED]':safeBody(v,depth+1);return out}if(typeof body==='string')return body.length>2000?body.slice(0,2000)+'…':body;return body};
  function bodyMeta(body){if(body==null)return{body:null,operationName:null};try{let p=body;if(typeof body==='string'){if(body.length>12000)return{body:'[BODY_TOO_LARGE]',operationName:null};try{p=JSON.parse(body)}catch{const q=new URLSearchParams(body),o={};for(const[k,v]of q)o[k]=SENSITIVE.test(k)?'[REDACTED]':String(v).slice(0,1000);p=Object.keys(o).length?o:body.slice(0,12000)}}else if(body instanceof URLSearchParams){p={};for(const[k,v]of body)p[k]=SENSITIVE.test(k)?'[REDACTED]':String(v).slice(0,1000)}else if(typeof FormData!=='undefined'&&body instanceof FormData)return{body:'[FormData]',operationName:null};const s=safeBody(p);return{body:s,operationName:s&&typeof s==='object'?(s.operationName||s.operation_name||null):null}}catch{return{body:'[UNREADABLE_BODY]',operationName:null}}}
  function requestMeta(url,method,body){let query={};try{const u=new URL(url,location.href);for(const[k,v]of u.searchParams)query[k]=SENSITIVE.test(k)?'[REDACTED]':String(v).slice(0,500)}catch{}const bm=bodyMeta(body);return{method:String(method||'GET').toUpperCase(),query,body:bm.body,operationName:bm.operationName}}
  function should(url,ct=''){const s=String(url||'');if(!s||NOISE.some(r=>r.test(s)))return false;if(/\.(?:js|css|png|jpe?g|gif|webp|svg|woff2?)(?:[?#]|$)/i.test(s))return false;return /json/i.test(ct)||/\/api\/|graphql|gql/i.test(s)||BUSINESS.test(s)}
  function emit(meta,text){const always=ALWAYS.some(r=>r.test(String(meta.url||'')));if((!enabled&&!always)||!text)return;let trim=String(text).trim();if(!/^[\[{]/.test(trim)&&!/json/i.test(meta.contentType||''))return;const detail={captureId:`${Date.now()}-${Math.random().toString(36).slice(2,8)}`,...meta,pageUrl:location.href,pageTitle:document.title,timestamp:new Date().toISOString(),responseChars:trim.length};if(trim.length<=1600000)detail.rawText=trim;else detail.oversized=true;window.postMessage({source:SOURCE,type:'NETWORK_CAPTURE',detail},'*')}
  window.addEventListener('message',e=>{if(e.source===window&&e.data?.source===SOURCE&&e.data?.type==='HOOK_STATE')enabled=!!e.data.enabled});
  const nativeFetch=window.fetch;window.fetch=async function(input,init={}){const reqUrl=typeof input==='string'?input:(input?.url||''),method=String(init.method||input?.method||'GET').toUpperCase(),req=requestMeta(reqUrl,method,init.body);const started=performance.now(),response=await nativeFetch.apply(this,arguments);const finalUrl=response.url||reqUrl,ct=response.headers.get('content-type')||'',always=ALWAYS.some(r=>r.test(finalUrl));if((enabled||always)&&should(finalUrl,ct)){try{const clone=response.clone();clone.text().then(text=>emit({transport:'fetch',url:finalUrl,endpoint:endpointOf(finalUrl),method,request:req,status:clone.status,ok:clone.ok,contentType:ct,durationMs:Math.round(performance.now()-started)},text)).catch(()=>{})}catch{}}return response};
  const xo=XMLHttpRequest.prototype.open,xs=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.open=function(method,url){this.__gs={method:String(method||'GET').toUpperCase(),url:String(url||''),started:0};return xo.apply(this,arguments)};XMLHttpRequest.prototype.send=function(body){const m=this.__gs||{method:'GET',url:''};m.started=performance.now();m.request=requestMeta(m.url,m.method,body);this.__gs=m;this.addEventListener('loadend',function(){try{const x=this.__gs||m,url=this.responseURL||x.url,ct=this.getResponseHeader('content-type')||'',always=ALWAYS.some(r=>r.test(url));if((!enabled&&!always)||!should(url,ct))return;let text='';if(!this.responseType||this.responseType==='text')text=this.responseText||'';else if(this.responseType==='json'&&this.response!=null)text=JSON.stringify(this.response);else return;emit({transport:'xhr',url,endpoint:endpointOf(url),method:x.method,request:x.request,status:this.status,ok:this.status>=200&&this.status<400,contentType:ct,durationMs:Math.round(performance.now()-x.started)},text)}catch{}},{once:true});return xs.apply(this,arguments)};
})();
