import {gestorApi} from './gestor-api.js';

export const JOB_KEY='gsJobsV1';
export async function loadJobs(){const x=await chrome.storage.local.get(JOB_KEY);return Array.isArray(x[JOB_KEY])?x[JOB_KEY]:[];}
export async function saveJobs(jobs){await chrome.storage.local.set({[JOB_KEY]:jobs});}
export async function upsertJob(job){const jobs=await loadJobs(),i=jobs.findIndex(x=>x.id===job.id),next={...job,updatedAt:new Date().toISOString()};if(i>=0)jobs[i]={...jobs[i],...next};else jobs.push(next);await saveJobs(jobs);return next;}
export async function createPeriodicJob({itemId,title,url,frequencyDays=7,policy}){const id=`listing:${itemId||btoa(url||title).replace(/=+$/,'')}`;const now=Date.now(),job={id,type:'listing_maintenance',itemId:itemId||null,title:title||'',url:url||'',status:'scheduled',frequencyDays:Math.max(1,Number(frequencyDays)||7),nextRunAt:new Date(now+Math.max(1,Number(frequencyDays)||7)*86400000).toISOString(),policy:policy||{},history:[]};await upsertJob(job);await chrome.alarms.create(`gs:${id}`,{when:new Date(job.nextRunAt).getTime(),periodInMinutes:job.frequencyDays*1440});return job;}
export async function cancelJob(id){const jobs=await loadJobs(),j=jobs.find(x=>x.id===id);if(j){j.status='cancelled';j.updatedAt=new Date().toISOString();await saveJobs(jobs);}await chrome.alarms.clear(`gs:${id}`);return j;}

async function syncRunToGestor(job,result){
  const audit=result?.audit,listing=audit?.listingAudit,analysis=listing?.analysis;if(!result?.ok||!analysis||!job?.itemId)return;
  const campaign=audit?.campaign||{},product=listing?.product||{},ctx=job.policy?.context||{};
  const next=new Date(Date.now()+Math.max(1,Number(job.frequencyDays)||10)*86400000);
  const metrics={visitors:Number.isFinite(Number(product.views))?Number(product.views):null,sales:Number.isFinite(Number(campaign.orders))?Number(campaign.orders):null,gmv:Number.isFinite(Number(campaign.gmv))?Number(campaign.gmv):null,spend:Number.isFinite(Number(campaign.spend))?Number(campaign.spend):null,roas:Number.isFinite(Number(campaign.roas))?Number(campaign.roas):null,targetRoas:Number.isFinite(Number(campaign.targetRoas))?Number(campaign.targetRoas):null,clicks:Number.isFinite(Number(campaign.clicks))?Number(campaign.clicks):null,impressions:Number.isFinite(Number(campaign.impressions))?Number(campaign.impressions):null};
  await gestorApi.saveAnalysisReport({item_id:Number(job.itemId),analyzed_at:new Date().toISOString(),next_reanalysis_at:next.toISOString(),frequency_days:job.frequencyDays,mode:job.policy?.mode==='automatic'?'automatic':'approve',extension_version:'0.9.0',source:'chrome-extension-periodic',objective:ctx.objective||null,situation:ctx.situation||null,bottleneck:ctx.bottleneck||null,score:analysis.score,product_snapshot:{...product,itemId:job.itemId,title:product.title||job.title,url:product.url||job.url},ads_snapshot:campaign,finance_snapshot:{},competitors:[],report:{score:analysis.score,summary:analysis.summary,dimensions:analysis.dimensions,lessons:analysis.lessons,priceInsight:analysis.priceInsight,roasStrategy:analysis.roasStrategy,cycleSummary:audit?.summary||null,executed:audit?.executed||[]},suggestions:{title:analysis.optimizedTitle,description:analysis.optimizedDescription,category:analysis.suggestedCategory},metrics,schedule_settings:job.policy||{}});
}

export async function markRun(id,result){const jobs=await loadJobs(),j=jobs.find(x=>x.id===id);if(!j)return null;j.lastRunAt=new Date().toISOString();j.nextRunAt=new Date(Date.now()+j.frequencyDays*86400000).toISOString();j.history=[...(j.history||[]),{at:j.lastRunAt,result}].slice(-30);j.status='scheduled';await saveJobs(jobs);try{await syncRunToGestor(j,result);}catch(e){console.warn('Gestor Senior: falha sincronizando reanálise web',e);}return j;}
