'use client';

import {useMemo,useState} from 'react';
import Link from 'next/link';
import styles from './page.module.css';

const n=v=>Number.isFinite(Number(v))?Number(v):null;
const money=v=>n(v)==null?'—':n(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const pct=v=>n(v)==null?'—':`${n(v).toLocaleString('pt-BR',{maximumFractionDigits:1})}%`;
const num=v=>n(v)==null?'—':n(v).toLocaleString('pt-BR',{maximumFractionDigits:2});
const date=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR');};
const shortDate=v=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});};
const firstImage=p=>p?.imageUrl||p?.image_url||p?.imageUrls?.[0]||p?.image?.image_url_list?.[0]||null;
const titleOf=r=>r?.product_snapshot?.title||r?.product_snapshot?.item_name||`Produto ${r?.item_id||''}`;
const metric=(r,k)=>r?.metrics?.[k]??r?.ads_snapshot?.manual?.[k]??r?.ads_snapshot?.[k]??null;
const finance=(r,k)=>r?.finance_snapshot?.[k]??r?.metrics?.[k]??null;
const productValue=(r,k)=>r?.product_snapshot?.[k]??null;
const safeArray=v=>Array.isArray(v)?v:[];
const TAB_META={ads:{label:'Shopee Ads',dot:'green',icon:'◎'},analysis:{label:'Super Análise',dot:'yellow',icon:'◔'},competitors:{label:'Concorrentes',dot:'red',icon:'◉'},suggestions:{label:'Sugestões',dot:'yellow',icon:'✦'},history:{label:'Histórico',dot:'gray',icon:'◷'},charts:{label:'Gráficos',dot:'blue',icon:'▥'}};

function delta(cur,prev){const a=n(cur),b=n(prev);if(a==null||b==null)return null;if(b===0)return a===0?0:null;return(a-b)/Math.abs(b)*100;}
function changeText(cur,prev,{lowerBetter=false,points=false}={}){const a=n(cur),b=n(prev);if(a==null||b==null)return{label:'—',tone:'neutral',arrow:'→'};const d=points?a-b:delta(a,b);if(d==null)return{label:'Novo',tone:'neutral',arrow:'→'};if(Math.abs(d)<.001)return{label:points?'0 p.p.':'0%',tone:'neutral',arrow:'→'};const good=lowerBetter?d<0:d>0;return{label:`${d>0?'+':''}${d.toFixed(1).replace('.',',')}${points?' p.p.':'%'}`,tone:good?'good':'bad',arrow:d>0?'↑':'↓'};}
function statusFor(row){if(row.current==null)return{label:'Sem dados',tone:'gray'};const d=changeText(row.current,row.previous,row.options);if(d.tone==='good')return{label:'Melhorou',tone:'green'};if(d.tone==='bad')return{label:row.critical?'Crítico':'Atenção',tone:'red'};return{label:'Estável',tone:'gray'};}
function gaugeTone(score){const s=n(score)||0;return s>=85?'good':s>=70?'warn':'bad';}
function lightFor(item){const latest=item.latest||{},prev=item.previous||{},score=n(latest.score),roas=n(metric(latest,'roas')),target=n(metric(latest,'targetRoas')),comp=safeArray(latest.competitors),prevComp=safeArray(prev.competitors);let danger=0,warn=0;if(score!=null&&score<70)danger++;else if(score!=null&&score<85)warn++;if(roas!=null&&target!=null&&roas<target*.8)danger++;else if(roas!=null&&target!=null&&roas<target)warn++;if(comp.some(c=>{const p=prevComp.find(x=>String(x.itemId??x.item_id)===String(c.itemId??c.item_id));return p&&n(c.price)!=null&&n(p.price)!=null&&n(c.price)<n(p.price)*.93;}))warn++;return danger?'red':warn?'yellow':'green';}

function Gauge({score,small=false}){const s=Math.max(0,Math.min(100,n(score)||0));return <div className={`${styles.gauge} ${styles[gaugeTone(s)]} ${small?styles.gaugeSmall:''}`} style={{'--score':`${s*1.8}deg`}}><div><b>{n(score)==null?'—':Math.round(s)}</b><span>/100</span></div></div>;}
function Dot({tone='gray'}){return <span className={`${styles.dot} ${styles[`dot${tone[0].toUpperCase()}${tone.slice(1)}`]||''}`}/>;}
function Trend({current,previous,lowerBetter=false,points=false}){const d=changeText(current,previous,{lowerBetter,points});return <span className={`${styles.trend} ${styles[d.tone]}`}>{d.arrow} {d.label}</span>;}

function Sidebar(){return <aside className={styles.sidebar}><div className={styles.sideBrand}><span>GS</span><div><b>Gestor Sênior</b><small>Shopee Intelligence</small></div></div><nav><Link href="/">⌂ <span>Dashboard</span></Link><Link className={styles.sideActive} href="/extensao-shopee-intelligence">▣ <span>Super Anúncio</span></Link><a href="#produtos">▤ <span>Relatórios</span></a><a href="#concorrentes">⌘ <span>Concorrentes</span></a><Link href="/produtos">▱ <span>Produtos</span></Link><a href="#reanálises">↻ <span>Reanálises</span></a><Link href="/">⚙ <span>Configurações</span></Link></nav></aside>;}

function Summary({items}){const avg=items.length?items.reduce((s,x)=>s+(n(x.latest?.score)||0),0)/items.length:0;const urgent=items.filter(x=>lightFor(x)==='red').length;const recheck=items.filter(x=>x.schedule?.enabled&&x.schedule?.next_run_at&&new Date(x.schedule.next_run_at)<=new Date(Date.now()+3*86400000)).length;const ads=items.filter(x=>{const r=n(metric(x.latest,'roas')),t=n(metric(x.latest,'targetRoas'));return r!=null&&t!=null&&r<t;}).length;const cards=[['▣','Anúncios analisados',items.length,'blue'],['☆','Nota média',items.length?avg.toFixed(1):'—','green'],['⚠','Reanálises urgentes',urgent,'red'],['♟','Concorrentes para rechecagem',recheck,'purple'],['●','Ads em atenção',ads,'yellow']];return <section className={styles.summary}>{cards.map(([icon,label,value,tone])=><div className={styles.kpi} key={label}><span className={`${styles.kpiIcon} ${styles[tone]}`}>{icon}</span><div><small>{label}</small><b>{value}</b></div></div>)}</section>;}

function ProductHeader({item,expanded,onToggle}){const r=item.latest||{},p=r.product_snapshot||{},img=firstImage(p),price=n(metric(r,'price')??productValue(r,'price')),cost=n(r.finance_snapshot?.productCost),margin=n(r.finance_snapshot?.marginPct??metric(r,'marginPct'));return <button className={`${styles.productRow} ${expanded?styles.productRowOpen:''}`} onClick={onToggle} type="button"><span className={styles.expand}>{expanded?'⌄':'›'}</span><span className={styles.productCell}>{img?<img src={img} alt=""/>:<span className={styles.noImg}/>}<span><b>{titleOf(r)}</b><small>ID: {item.itemId}</small></span></span><span><small>Preço</small><b>{money(price)}</b></span><span><small>Custo</small><b>{money(cost)}</b></span><span><small>Categoria</small><b>{p.category||'—'}</b></span><span className={styles.gaugeCell}><small>Super Análise</small><Gauge score={r.score} small/></span><span><small>ROAS atual</small><b>{num(metric(r,'roas'))}</b></span><span><small>ROAS alvo</small><b>{num(metric(r,'targetRoas'))}</b></span><span><small>GMV</small><b>{money(metric(r,'gmv'))}</b></span><span><small>Custo por venda</small><b>{money(metric(r,'cpa')??(n(metric(r,'sales'))?n(metric(r,'spend'))/n(metric(r,'sales')):null))}</b></span><span><small>Margem</small><b className={margin!=null&&margin<0?styles.bad:styles.good}>{pct(margin)}</b></span><span><small>Última análise</small><b>{date(r.analyzed_at)}</b></span></button>;}

function TabBar({active,setActive,item,onExport,onCloud}){const light=lightFor(item);return <div className={styles.tabLine}><div className={styles.tabs}>{Object.entries(TAB_META).map(([key,m])=><button key={key} className={`${styles.tab} ${active===key?styles.tabActive:''}`} onClick={()=>setActive(key)}><Dot tone={key==='ads'?light:m.dot}/><span>{m.icon} {m.label}</span></button>)}</div><div className={styles.dataActions}><button onClick={onCloud}>☁ Salvar na nuvem</button><button onClick={onExport}>⇩ Exportar</button></div></div>;}

function AdsPanel({item}){const cur=item.latest||{},prev=item.previous||{};const rows=[
  {label:'ROAS alvo',current:metric(cur,'targetRoas'),previous:metric(prev,'targetRoas'),format:num,obs:'Compare a meta com o ROAS realmente entregue antes de alterar.'},
  {label:'ROAS entregue',current:metric(cur,'roas'),previous:metric(prev,'roas'),format:num,critical:true,obs:'Acompanhe se a campanha está entregando a meta definida.'},
  {label:'Gasto Ads',current:metric(cur,'spend'),previous:metric(prev,'spend'),format:money,options:{lowerBetter:true},obs:'Gasto deve ser analisado junto de GMV, pedidos e ROAS.'},
  {label:'Custo por venda',current:metric(cur,'cpa')??(n(metric(cur,'sales'))?n(metric(cur,'spend'))/n(metric(cur,'sales')):null),previous:metric(prev,'cpa')??(n(metric(prev,'sales'))?n(metric(prev,'spend'))/n(metric(prev,'sales')):null),format:money,options:{lowerBetter:true},critical:true,obs:'Quanto menor, melhor, desde que volume e margem sejam preservados.'},
  {label:'CTR',current:metric(cur,'ctr'),previous:metric(prev,'ctr'),format:pct,options:{points:true},obs:'Ajuda a indicar interesse no anúncio e nos criativos.'},
  {label:'Preço',current:metric(cur,'price')??productValue(cur,'price'),previous:metric(prev,'price')??productValue(prev,'price'),format:money,obs:'Mudanças de preço devem ser avaliadas junto da margem e concorrência.'},
  {label:'Margem %',current:finance(cur,'marginPct'),previous:finance(prev,'marginPct'),format:pct,obs:'Margem percentual estimada depois do custo e do Ads.'},
  {label:'Margem R$',current:finance(cur,'profit')??metric(cur,'marginR'),previous:finance(prev,'profit')??metric(prev,'marginR'),format:money,obs:'Lucro estimado por venda no cenário analisado.'}
];
  const cards=[rows[0],rows[1],rows[2],rows[3],rows[4],rows[5],rows[6],rows[7]];
  const status=rows.filter(r=>statusFor(r).tone==='red').length?'Atenção':rows.some(r=>statusFor(r).tone==='gray')?'Parcial':'Excelente';
  return <section className={styles.panel}><div className={styles.panelHead}><div><h3><Dot tone="green"/> Shopee Ads</h3><p>Desempenho dos anúncios na Shopee</p></div><div className={styles.dateStrip}><span>▣ Última análise: {date(cur.analyzed_at)}</span><span>↻ Próxima reanálise: {date(item.schedule?.next_run_at||cur.next_reanalysis_at)}</span></div></div><div className={styles.metricCards}>{cards.map(r=><div className={styles.metricCard} key={r.label}><small>{r.label}</small><b>{r.format(r.current)}</b><Trend current={r.current} previous={r.previous} lowerBetter={r.options?.lowerBetter} points={r.options?.points}/></div>)}<div className={styles.metricCard}><small>Status geral</small><b className={status==='Excelente'?styles.good:styles.warn}><Dot tone={status==='Excelente'?'green':'yellow'}/> {status}</b></div></div><div className={styles.dataTableWrap}><table className={styles.dataTable}><thead><tr><th>Indicador</th><th>Anterior</th><th>Atual</th><th>Variação</th><th>Status</th><th>Observação</th></tr></thead><tbody>{rows.map(r=>{const st=statusFor(r);const d=changeText(r.current,r.previous,r.options);return <tr key={r.label}><td><b>{r.label}</b></td><td>{r.format(r.previous)}</td><td>{r.format(r.current)}</td><td><span className={`${styles.trend} ${styles[d.tone]}`}>{d.arrow} {d.label}</span></td><td><span className={styles.statusCell}><Dot tone={st.tone}/>{st.label}</span></td><td>{r.obs}</td></tr>})}</tbody></table></div></section>;}

function AnalysisPanel({item}){const r=item.latest||{},dims=safeArray(r.report?.dimensions);return <section className={styles.panel}><div className={styles.panelHead}><div><h3><Dot tone={gaugeTone(r.score)==='good'?'green':gaugeTone(r.score)==='warn'?'yellow':'red'}/> Super Análise</h3><p>Diagnóstico por critério, nota geral e data da rodada</p></div><div className={styles.dateStrip}>Última análise: {date(r.analyzed_at)}</div></div><div className={styles.analysisLayout}><div className={styles.bigGauge}><Gauge score={r.score}/><p>{r.report?.summary||'Sem resumo salvo.'}</p></div><div className={styles.criteria}>{dims.map((d,i)=>{const ratio=n(d.score)&&n(d.maxScore)?n(d.score)/n(d.maxScore):0;return <div className={styles.criterion} key={`${d.name}-${i}`}><div><b>{d.name}</b><span>{d.score}/{d.maxScore}</span></div><div className={styles.bar}><i style={{width:`${Math.max(0,Math.min(100,ratio*100))}%`}}/></div><p>{d.reason}</p></div>})}</div></div></section>;}

function competitorId(c){return String(c?.itemId??c?.item_id??c?.id??'');}
function competitorLink(c){return c?.link||c?.url||c?.productUrl||'';}
function CompetitorsPanel({item}){const cur=item.latest||{},prev=item.previous||{},rows=safeArray(cur.competitors).slice(0,3),prevRows=safeArray(prev.competitors);const insights=cur.report?.competitorInsights||{};return <section className={styles.panel} id="concorrentes"><div className={styles.panelHead}><div><h3><Dot tone="red"/> Concorrentes</h3><p>Preço, vendas, data da coleta, histórico e acesso direto ao anúncio</p></div><div className={styles.dateStrip}>Coleta da rodada: {date(cur.analyzed_at)}</div></div><div className={styles.dataTableWrap}><table className={styles.dataTable}><thead><tr><th>Concorrente</th><th>Preço</th><th>Vendas</th><th>Data da coleta</th><th>Δ preço</th><th>Δ vendas</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.length?rows.map((c,i)=>{const old=prevRows.find(x=>competitorId(x)&&competitorId(x)===competitorId(c))||prevRows[i],pd=changeText(c.price,old?.price,{lowerBetter:false}),sd=changeText(c.sold??c.historicalSold,old?.sold??old?.historicalSold);const url=competitorLink(c);return <tr key={competitorId(c)||i}><td><b>{c.title||c.name||`Concorrente ${i+1}`}</b></td><td>{money(c.price)}</td><td>{num(c.sold??c.historicalSold)}</td><td>{date(cur.analyzed_at)}</td><td><span className={`${styles.trend} ${styles[pd.tone]}`}>{pd.arrow} {pd.label}</span></td><td><span className={`${styles.trend} ${styles[sd.tone]}`}>{sd.arrow} {sd.label}</span></td><td><span className={styles.statusCell}><Dot tone={n(c.price)!=null&&n(productValue(cur,'price'))!=null&&n(c.price)<n(productValue(cur,'price'))?'red':'green'}/>{n(c.price)!=null&&n(productValue(cur,'price'))!=null&&n(c.price)<n(productValue(cur,'price'))?'Mais barato':'Monitorar'}</span></td><td>{url?<a className={styles.linkButton} href={url} target="_blank" rel="noreferrer">↗ Abrir</a>:<span className={styles.muted}>Sem link</span>}</td></tr>}):<tr><td colSpan="8">Nenhum concorrente salvo nesta rodada.</td></tr>}</tbody></table></div><div className={styles.insightGrid}><div><b>🏆 Pontos fortes</b><ul>{safeArray(insights.strengths).length?safeArray(insights.strengths).map((x,i)=><li key={i}>{x}</li>):<li>Compare preço, avaliações, vendas e estrutura dos títulos.</li>}</ul></div><div><b>⌕ Semelhanças</b><ul>{safeArray(insights.similarities).length?safeArray(insights.similarities).map((x,i)=><li key={i}>{x}</li>):<li>Mesmos termos, faixa de preço e formato podem indicar concorrência direta.</li>}</ul></div><div><b>💡 Oportunidades</b><ul>{safeArray(insights.opportunities).length?safeArray(insights.opportunities).map((x,i)=><li key={i}>{x}</li>):<li>Use os diferenciais reais dos concorrentes para melhorar o anúncio sem copiar conteúdo.</li>}</ul></div></div></section>;}

function SuggestionsPanel({item}){const r=item.latest||{},s=r.suggestions||{},ins=r.report?.competitorInsights||{};const [open,setOpen]=useState(null);const sections=[['title','Título sugerido',s.title],['description','Descrição sugerida',s.description],['category','Categoria sugerida',s.category],['competitors','Comparação com concorrentes',[...safeArray(ins.strengths),...safeArray(ins.similarities),...safeArray(ins.opportunities)].join('\n• ')]];return <section className={styles.panel}><div className={styles.panelHead}><div><h3><Dot tone="yellow"/> Sugestões</h3><p>Conteúdo permanece recolhido para não poluir a tela</p></div></div><div className={styles.suggestionButtons}>{sections.map(([key,label])=><button key={key} className={open===key?styles.suggestionActive:''} onClick={()=>setOpen(open===key?null:key)}>▧ Ver {label.toLowerCase()}</button>)}</div>{open&&<div className={styles.suggestionBody}><b>{sections.find(x=>x[0]===open)?.[1]}</b><pre>{sections.find(x=>x[0]===open)?.[2]||'Sem sugestão salva nesta rodada.'}</pre></div>}</section>;}

function HistoryPanel({item}){const history=safeArray(item.history);return <section className={styles.panel}><div className={styles.panelHead}><div><h3><Dot tone="gray"/> Histórico</h3><p>Todas as Super Análises preservadas, inclusive a primeira</p></div><div className={styles.dateStrip}>{history.length} análise(s)</div></div><div className={styles.dataTableWrap}><table className={styles.dataTable}><thead><tr><th>Data</th><th>Nota</th><th>Preço</th><th>Vendas</th><th>ROAS alvo</th><th>ROAS entregue</th><th>GMV</th><th>Margem</th></tr></thead><tbody>{history.map(r=><tr key={r.id}><td>{date(r.analyzed_at)}</td><td><b>{r.score??'—'}/100</b></td><td>{money(metric(r,'price')??productValue(r,'price'))}</td><td>{num(metric(r,'sales')??metric(r,'sold'))}</td><td>{num(metric(r,'targetRoas'))}</td><td>{num(metric(r,'roas'))}</td><td>{money(metric(r,'gmv'))}</td><td>{pct(finance(r,'marginPct'))}</td></tr>)}</tbody></table></div></section>;}

const CHARTS={sales:{label:'Vendas',color:'#16a366',value:r=>metric(r,'sales')??metric(r,'sold')},price:{label:'Preço (R$)',color:'#2d6cdf',value:r=>metric(r,'price')??productValue(r,'price')},target:{label:'ROAS alvo',color:'#7c4dff',value:r=>metric(r,'targetRoas')},roas:{label:'ROAS atingido',color:'#ee8a1c',value:r=>metric(r,'roas')},score:{label:'Nota da Super Análise',color:'#e63845',value:r=>r.score},gmv:{label:'GMV (R$)',color:'#4b84a4',value:r=>metric(r,'gmv')}};
function ChartsPanel({item}){const history=[...safeArray(item.history)].reverse();const [selected,setSelected]=useState(new Set(['sales','price','target','roas','score']));const width=900,height=300,pad=34;const toggle=k=>setSelected(s=>{const x=new Set(s);x.has(k)?x.delete(k):x.add(k);return x;});const paths=[];for(const [key,m] of Object.entries(CHARTS)){if(!selected.has(key))continue;const vals=history.map(r=>n(m.value(r)));const finite=vals.filter(v=>v!=null),min=finite.length?Math.min(...finite):0,max=finite.length?Math.max(...finite):1,span=max-min||1;const pts=vals.map((v,i)=>{if(v==null)return null;const x=pad+(width-pad*2)*(history.length<=1?.5:i/(history.length-1));const y=height-pad-(height-pad*2)*((v-min)/span);return{x,y,v,r:history[i]};}).filter(Boolean);const d=pts.map((p,i)=>`${i?'L':'M'}${p.x.toFixed(1)},${p.y.toFixed(1)}`).join(' ');paths.push({key,m,pts,d});}
  const first=history[0],last=history.at(-1);const insights=[];for(const k of ['score','price','roas']){const m=CHARTS[k],d=changeText(m.value(last),m.value(first));if(d.label!=='—')insights.push({label:m.label,d});}
  return <section className={styles.panel}><div className={styles.panelHead}><div><h3><Dot tone="blue"/> Gráficos</h3><p>Acompanhe a evolução dos principais indicadores ao longo do tempo</p></div><div className={styles.dateStrip}>{history.length?`${shortDate(history[0].analyzed_at)} — ${shortDate(history.at(-1).analyzed_at)}`:'Sem histórico'}</div></div><div className={styles.chartToggles}>{Object.entries(CHARTS).map(([k,m])=><button key={k} className={selected.has(k)?styles.chartOn:''} onClick={()=>toggle(k)} style={{'--series':m.color}}><span/> {m.label}</button>)}</div><div className={styles.chartLayout}><div className={styles.chartBox}>{history.length<2?<div className={styles.emptyChart}>O gráfico aparecerá depois de pelo menos duas análises.</div>:<svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label="Evolução das métricas">{[0,1,2,3,4].map(i=><line key={i} x1={pad} y1={pad+i*(height-pad*2)/4} x2={width-pad} y2={pad+i*(height-pad*2)/4} className={styles.gridLine}/>) }{paths.map(x=><g key={x.key}><path d={x.d} fill="none" stroke={x.m.color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/>{x.pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="4" fill={x.m.color}><title>{`${x.m.label}: ${p.v} · ${date(p.r.analyzed_at)}`}</title></circle>)}</g>)}{history.map((r,i)=>{const x=pad+(width-pad*2)*(history.length<=1?.5:i/(history.length-1));return <text key={r.id} x={x} y={height-8} textAnchor="middle" className={styles.axisText}>{shortDate(r.analyzed_at)}</text>})}</svg>}</div><aside className={styles.chartInsights}><b>💡 Principais insights</b>{insights.map((x,i)=><div key={i}><span className={`${styles.trend} ${styles[x.d.tone]}`}>{x.d.arrow}</span><p><b>{x.label}</b><small>{x.d.label} entre a primeira e a última análise exibida.</small></p></div>)}</aside></div></section>;}

function ActivePanel({tab,item}){if(tab==='ads')return <AdsPanel item={item}/>;if(tab==='analysis')return <AnalysisPanel item={item}/>;if(tab==='competitors')return <CompetitorsPanel item={item}/>;if(tab==='suggestions')return <SuggestionsPanel item={item}/>;if(tab==='history')return <HistoryPanel item={item}/>;return <ChartsPanel item={item}/>;}

function exportJson(items){const blob=new Blob([JSON.stringify(items,null,2)],{type:'application/json'});downloadBlob(blob,`super-anuncio-backup-${new Date().toISOString().slice(0,10)}.json`);}
function exportCsv(items){const header=['item_id','titulo','data','nota','preco','custo','margem_pct','roas_alvo','roas_entregue','gmv','gasto_ads','vendas'];const rows=[header.join(';')];for(const x of items){for(const r of safeArray(x.history)){const p=r.product_snapshot||{},vals=[x.itemId,titleOf(r),r.analyzed_at,r.score,metric(r,'price')??p.price,r.finance_snapshot?.productCost,finance(r,'marginPct'),metric(r,'targetRoas'),metric(r,'roas'),metric(r,'gmv'),metric(r,'spend'),metric(r,'sales')];rows.push(vals.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(';'));}}downloadBlob(new Blob(['\ufeff'+rows.join('\n')],{type:'text/csv;charset=utf-8'}),`super-anuncio-${new Date().toISOString().slice(0,10)}.csv`);}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

export default function SuperAnuncioDashboard({items:sourceItems=[],shopName=''}){const [query,setQuery]=useState('');const [expanded,setExpanded]=useState(sourceItems[0]?.itemId||null);const [activeTab,setActiveTab]=useState('ads');const [notice,setNotice]=useState('');const [exportOpen,setExportOpen]=useState(false);const items=useMemo(()=>sourceItems.filter(x=>titleOf(x.latest).toLowerCase().includes(query.trim().toLowerCase())||String(x.itemId).includes(query.trim())),[sourceItems,query]);const cloud=()=>{setNotice('✓ As análises já ficam salvas automaticamente na nuvem do Gestor Sênior.');setTimeout(()=>setNotice(''),3500);};return <div className={styles.shell}><Sidebar/><main className={styles.page}><header className={styles.top}><div className={styles.brand}><div className={styles.logo}>▥</div><div><h1>Super Anúncio</h1><p>Histórico, reanálises e concorrentes{shopName?` · ${shopName}`:''}</p></div></div><div className={styles.topTools}><label className={styles.search}>⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar por título do produto ou ID..."/></label><Link className={styles.back} href="/">← Voltar ao Gestor</Link></div></header><Summary items={sourceItems}/><section className={styles.listCard} id="produtos"><div className={styles.listTitle}><h2>Produtos analisados ({items.length})</h2><span>{sourceItems.length} no histórico da nuvem</span></div>{!items.length?<div className={styles.empty}>Nenhuma análise encontrada.</div>:items.map(item=>{const isOpen=expanded===item.itemId;return <article className={styles.item} key={item.itemId}><ProductHeader item={item} expanded={isOpen} onToggle={()=>{setExpanded(isOpen?null:item.itemId);if(!isOpen)setActiveTab('ads');}}/>{isOpen&&<><TabBar active={activeTab} setActive={setActiveTab} item={item} onCloud={cloud} onExport={()=>setExportOpen(v=>!v)}/>{exportOpen&&<div className={styles.exportMenu}><button onClick={()=>{exportJson(sourceItems);setExportOpen(false)}}>Backup completo (.json)</button><button onClick={()=>{exportCsv(sourceItems);setExportOpen(false)}}>Planilha (.csv)</button></div>}<ActivePanel tab={activeTab} item={item}/></>}</article>})}</section>{notice&&<div className={styles.toast}>{notice}</div>}</main></div>;}
