import PublicInfoLayout from '../components/PublicInfoLayout';
import styles from '../public-info.module.css';
export const metadata={title:'Política de Privacidade | Gestor Sênior'};
export default function Page(){
 return <PublicInfoLayout eyebrow="Privacidade" title="Política de Privacidade" lead="Versão de preparação para operação multiusuário — atualizada em 25 de setembro de 2026.">
  <section className={styles.section}><h2>1. Escopo</h2><p>Esta política descreve o tratamento de dados no Gestor Sênior, plataforma de gestão para vendedores Shopee. Ela deve ser revisada novamente antes da abertura comercial ampla, especialmente quanto ao canal oficial de contato, prazos legais de retenção e fornecedores adicionais que venham a ser contratados.</p></section>
  <section className={styles.section}><h2>2. Dados tratados</h2><ul><li>Dados de conta: nome e e-mail cadastrados no Gestor Sênior.</li><li>Dados de autenticação: a senha é processada pelo serviço de autenticação do Supabase; o Gestor não mantém senha em texto legível.</li><li>Dados da loja autorizada: identificador da loja e credenciais OAuth necessárias para a integração.</li><li>Dados operacionais consultados conforme as funções usadas no painel, como produtos, pedidos, estoque, campanhas e métricas disponibilizadas pela Shopee.</li><li>Dados técnicos mínimos de sessão e atividade usados para segurança e administração do serviço.</li></ul></section>
  <section className={styles.section}><h2>3. Finalidades</h2><p>Os dados são usados para autenticar o usuário, vincular a loja que ele autorizou, fornecer as funções solicitadas no painel, manter a sessão, diagnosticar falhas e proteger o acesso entre contas diferentes.</p></section>
  <section className={styles.section}><h2>4. Infraestrutura e segurança</h2><p>O aplicativo é hospedado na Vercel e usa Supabase para autenticação e banco de dados. A sessão do Gestor Sênior é mantida em cookie HttpOnly assinado. Credenciais da Shopee e chaves de serviço são processadas no servidor e não são enviadas ao navegador como parte da sessão.</p><p>O fluxo de autorização da Shopee usa um estado temporário vinculado à conta autenticada, reduzindo o risco de uma autorização ser associada ao usuário errado.</p></section>
  <section className={styles.section}><h2>5. Compartilhamento e operadores</h2><p>Os dados podem ser processados pelos provedores técnicos necessários ao serviço, atualmente Vercel e Supabase, além da própria Shopee no contexto da integração autorizada. Não declaramos venda de dados pessoais a terceiros.</p></section>
  <section className={styles.section}><h2>6. Retenção e exclusão</h2><p>Os dados são mantidos enquanto necessários para manter a conta e a integração, observadas obrigações legais aplicáveis. A política definitiva de prazos e o procedimento formal de solicitação de exclusão serão publicados antes da abertura comercial ampla.</p></section>
  <section className={styles.section}><h2>7. Direitos do titular</h2><p>Solicitações de acesso, correção, portabilidade, oposição, revogação de consentimento ou exclusão serão tratadas conforme a legislação aplicável. O canal oficial de privacidade será publicado nesta página antes da abertura comercial ampla.</p></section>
 </PublicInfoLayout>
}